SELECT ?var1  ?var1Label  ?var2 
WHERE {
  ?var1 ( <http://www.wikidata.org/prop/direct/P31> / <http://www.wikidata.org/prop/direct/P279> *) <http://www.wikidata.org/entity/Q12876> .
 OPTIONAL {
  BIND (  True
 AS  ?var3 ).
  ?var1  <http://www.wikidata.org/prop/direct/P495>  <http://www.wikidata.org/entity/Q142> .
 }
 OPTIONAL {
  BIND (  True
 AS  ?var3 ).
  ?var1  <http://www.wikidata.org/prop/direct/P176>  ?var4 .
  ?var4  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q142> .
 }
 FILTER (  (  BOUND (  ?var3  )  ) 
) .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en,en".
  }
}
