#ranking(s) of university(es)
#defaultView:LineChart
SELECT ?year ?ranking ?universityLabel ?deternimationMethodLabel ?university 
WHERE {
  VALUES ?university { wd:Q832355 wd:Q1108197 wd:Q16952 wd:Q16955 # to add another university # 1,uncomment the last commented line,  # 2,put cursor to the end of line,  # 3,and press CTRL+SPACE，or CTRL+ALT+SPACE, or ALT+ENTER.  # 4,and select first item, and press CTRL+ENTER. #wd:Zhejiang_University }
  VALUES ?deternimationMethod { wd:Q478743 # to add another deternimationMethod # 1,uncomment the last commented line,  # 2,put cursor to the end of line,  # 3,and press CTRL+SPACE，or CTRL+ALT+SPACE, or ALT+ENTER.  # 4,and select first item, and press CTRL+ENTER. #wd:Shanghai_Academic_Ranking_of_World_Universities }
  ?university p:P1352 ?statement .
  ?statement ps:P1352 ?ranking .
  ?statement pq:P459 ?deternimationMethod .
  ?statement pq:P585 ?date .
  BIND (STR(YEAR(?date)) AS ?year)
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE], mul, en" .
  }
}
