FROM node:22-bookworm-slim@sha256:426d99333b9d35f568cc604b604ea484aef7d12b21e78a36c4bfbdf5cfa4afe2 AS build-editor

RUN apt update -y
COPY ./editor /src
WORKDIR /src
RUN npm install

CMD ["npm", "run", "serve"]
