FROM debian
FROM node:22-bookworm-slim@sha256:426d99333b9d35f568cc604b604ea484aef7d12b21e78a36c4bfbdf5cfa4afe2 AS build-editor

RUN apt update -y
COPY ./editor /src
WORKDIR /src
RUN npm install
RUN npm run build

FROM node:22-bookworm-slim@sha256:426d99333b9d35f568cc604b604ea484aef7d12b21e78a36c4bfbdf5cfa4afe2 AS deploy
WORKDIR /deploy
COPY --from=build-editor /src/build/ ./build
COPY --from=build-editor /src/package.json .
COPY --from=build-editor /src/package-lock.json .
RUN npm ci --omit dev

CMD ["node", "build"]
